apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grpc-project
  description: gRPC project with generated documentation.
spec:
  type: grpc
  lifecycle: production
  owner: user:guest
  links:
    - url: http://localhost:5000/grpc-docs/index.html
      title: gRPC Documentation
