apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grpc-project # The name of the component as it will appear in Backstage.
  description: gRPC project with generated documentation. # A brief description of the component.
  annotations:
    # This annotation tells Backstage where to find the TechDocs documentation for this component.
    # this could also be `url:<url>` if the documentation isn't in the same location
    #backstage.io/techdocs-ref: url:https://github.com/parmendes/GrpcProject/tree/main/apis/url
    backstage.io/techdocs-ref: dir:. # The directory where the TechDocs documentation is located.
spec:
  type: grpc # The type of the component (e.g., service, library, grpc, etc.).
  lifecycle: production # The lifecycle stage of the component (e.g., experimental, production, deprecated).
  owner: user:guest # The owner of the component, typically a user or team in Backstage.